name: code

on:
  push:
  pull_request:
  schedule:
    - cron: '0 20 * * 0'

defaults:
  run:
    shell: bash

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v -mod=vendor ./...

    - name: Test
      run: go test -v -mod=vendor ./...
